apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    app: debug-pod
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: debug-pod
    imagePullPolicy: Always
    tty: true
    image: ledfan/debug-pod
